### ISSUE TITLE
main method not found

### ISSUE THREAD

**Issue by HarshaCV** [rutujar/Doctor-records-using-B-tree-technique#1]
when running the project in eclipse it says main method not found what to do

**Comment by rutujar** [comment]
Pls share the code,i can look into it.

**Comment by HarshaCV** [comment]
https://github.com/rutujar/Doctor-records-using-B-plus-tree-technique/tree/master/Front%20end
The code link to the github

**Comment by rutujar** [comment]
actually i worked in Netbeans not in eclipse, it might be some bug or application issue. try using Netbeans IDE it will be easy

**Comment by HarshaCV** [comment]
Thank you for ur reply.I will try it and keep you posted.

**Comment by HarshaCV** [comment]
Found the solution.
Just need to run it in a terminal
